import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from "@/components/shared/provider";
import Navbar from "@/components/shared/Navbar";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Meetmax",
  description: "Generated by Meetmax",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {" "}
        <Providers>
          <Navbar />
          <div className="h-[calc(100dvh-78px)] overflow-x-hidden overflow-y-auto">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
